config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from petitions import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('petitions/', include('petitions.urls')),
    path('accounts/', include('accounts.urls')),
    path('qna/', include('qna.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

petitions/urls.py
from django.urls import path
from petitions import views

app_name = 'petitions'

urlpatterns = [
    path('<int:petition_id>/', views.petition_detail, name='petition_detail'),
    # path('create/', views.petition_create, name='petition_create'),   # 상명대학교 청원 운영 종료
    path('modify/<int:petition_id>/', views.petition_modify, name='petition_modify'),
    path('delete/<int:petition_id>/', views.petition_delete, name='petition_delete'),
    path('vote/<int:petition_id>/', views.petition_vote, name='petition_vote'),
    path('status/<str:status>/', views.petition_list, name='petition_list'),

    path('comment/create/<int:petition_id>/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    path('answer/create/<int:petition_id>/', views.answer_create, name='answer_create'),
    path('answer/create/<int:petition_id>/<str:type>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

qna/urls.py
from django.urls import path

from qna import views

app_name = 'qna'

urlpatterns = [
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('questions/', views.question_list, name='question_list'),
    path('questions/<int:question_id>/', views.question_detail, name='question_detail'),
    # path('questions/create/', views.question_create, name='question_create'),
    path('questions/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('questions/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

petitions/models.py
from datetime import datetime

import pytz
from django.db import models
from django.contrib.auth.models import User

from accounts.models import Profile
from config.settings import CATEGORY_CHOICES, STATUS_CHOICES, TIME_ZONE, SUCCESS_VALUE


class Petition(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_petition')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)
    anonymous = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)

    def __str__(self):
        return f'[{self.author}] {self.subject} ({self.create_date})'

    def author_name(self):
        if self.anonymous:
            return '익명'
        profile = Profile.objects.filter(user=self.author)
        if profile:
            return profile.first().name
        return self.author.username

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)

    def end_date_str(self):
        return date_format(self.end_date)

    def period_str(self):
        return f'{date_format(self.create_date)} ~ {date_format(self.end_date)}'

    def d_day(self):
        if self.status == 1:
            day = (self.end_date.date() - datetime.now().date()).days
            day = day if day != 0 else 'Day'
            return f'| D-{day}'
        return ''

    def get_percentage(self):
        return 100 if self.voter.count() >= int(SUCCESS_VALUE) else (self.voter.count() * 100) // int(SUCCESS_VALUE)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    petition = models.ForeignKey(Petition, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'[{self.petition.subject}] {self.content} ({self.create_date})'

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='petition_answer')
    petition = models.ForeignKey(Petition, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'[{self.author}] {self.petition.subject} ({self.create_date})'

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)


def time_format(time):
    return time.astimezone(pytz.timezone(TIME_ZONE)).strftime("%m/%d %H:%M")


def date_format(time):
    return time.astimezone(pytz.timezone(TIME_ZONE)).strftime("%y.%m.%d")

qna/models.py
import pytz
from django.contrib.auth.models import User
from django.db import models
from accounts.models import Profile
from config.settings import TIME_ZONE


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    anonymous = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'[{self.author}] {self.subject} ({self.create_date})'

    def author_name(self):
        if self.anonymous:
            return '익명'
        profile = Profile.objects.filter(user=self.author)
        if profile:
            return profile.first().name
        return self.author.username

    def date_str(self):
        return date_format(self.create_date)

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='question_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'[{self.question.subject}] {self.content} ({self.create_date})'

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)


def time_format(time):
    return time.astimezone(pytz.timezone(TIME_ZONE)).strftime("%m/%d %H:%M")


def date_format(time):
    return time.astimezone(pytz.timezone(TIME_ZONE)).strftime("%y.%m.%d")

qna/forms.py
from django import forms
from qna.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content', 'anonymous']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

qna/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from petitions.decorators import superuser_required
from qna.forms import QuestionForm, AnswerForm
from qna.models import Question, Answer


def question_list(request):
    ql = Question.objects.all().order_by('-create_date')
    page = request.GET.get('page', '1')
    paginator = Paginator(ql, 5)
    page_obj = paginator.get_page(page)
    return render(request, 'qna/question_list.html', {'question_list': page_obj})


def question_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    answers = Answer.objects.filter(question=question)
    if answers:
        context['answer'] = answers.first()
    return render(request, 'qna/question_detail.html', context)


@login_required
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect('qna:question_list')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'qna/question_form.html', context)


@login_required
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('qna:question_detail', question_id=question.pk)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            petition = form.save(commit=False)
            petition.modify_date = timezone.now()
            petition.save()
            return redirect('qna:question_detail', question_id=question.pk)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'qna/question_form.html', context)


@login_required
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('qna:question_detail', question_id=question.id)
    question.delete()
    return redirect('qna:question_list')


@superuser_required
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if Answer.objects.filter(question=question):
        messages.error(request, '이미 답변한 질문 입니다.')
        return redirect('qna:question_detail', question_id=question.pk)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.question = question
            answer.save()
            return redirect('qna:question_detail', question_id=question.pk)
    else:
        form = AnswerForm()
    return render(request, 'qna/answer_form.html', {'form': form, 'question': question})


@superuser_required
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('qna:question_detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'qna/answer_form.html', {'form': form, 'question': answer.question})


@superuser_required
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('qna:question_detail', question_id=answer.question.id)


def terms(request):
    return render(request, 'qna/terms.html')


def privacy(request):
    return render(request, 'qna/privacy.html')

templates/qna/question_detail.html
{% extends 'base.html' %}
{% load static %}
{% load petitions_filter %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">청원 게시판</span>
            <span class="navbar-img__text--subtitle">상명대학교 학우 여러분들의 의견에</span>
            <span class="navbar-img__text--subtitle">귀를 기울이는 학생회가 되겠습니다.</span>
        </div>
    </div>
    <div>
        <div class="post_detail__title_container container my-3">
            <!-- message 표시 -->
            {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                <div class="alert alert-danger my-3" role="alert">
                    <strong>{{ message.tags }}</strong>
                    <ul><li>{{ message.message }}</li></ul>
                </div>
                {% endif %}
            {% endfor %}
            {% endif %}
            <!-- 청원 -->
            <div class="post_detail__title">
                {% if question.answer_set.count == 0 %}
                    <h4 class="py-2 post_detail__title-status table-body__proceeding" style="margin-bottom: 0;">[접수]</h4>
                {% else %}
                    <h4 class="py-2 post_detail__title-status table-body__complete" style="margin-bottom: 0;">[답변완료]</h4>
                {% endif %}
                <h3 class="py-2 post_detail__title-title" style="text-align: center; margin-top: 16px; margin-bottom: 0;">{{ question.subject }}</h3>
            </div>
        </div>

    <div class="post_detail__body_container container my-3" style="margin-bottom: 3rem !important;">
        <div class="post_detail__body-title border-bottom">
            <h4 class="post_detail__title-title my-3 py-2">청원내용</h4>
            <div class="post_detail__body-title--button">
                {% if request.user.is_superuser and not answer %}
                    <a href="{% url 'qna:answer_create' question.pk %}" class="btn btn-sm btn-primary">답변 등록</a>
                {% endif %}
                {% if request.user == question.author %}
                    <a href="{% url 'qna:question_modify' question.pk %}" class="btn btn-sm btn btn-warning">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-danger"
                        data-uri="{% url 'qna:question_delete' question.pk %}">삭제</a>
                {% endif %}
            </div>
        </div>
        <div class="card my-3">
            <div class="card-body">
                <div class="post_detail__body-text card-text">
                    {{ question.content|mark }}
                </div>
            </div>
            <div class="d-flex justify-content-end" style="margin-bottom: 0.5rem;">
                <div class="badge bg-light text-dark p-2 text-start">
                    {{ question.author_name }}
                </div>
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    {% if question.modify_date %}
                        {{ question.modify_date_str }} (수정)
                    {% else %}
                        {{ question.create_date_str }}
                    {% endif %}
                </div>
            </div>
        </div>

        {% if answer %}
            <div class="post_detail__body-title border-bottom">
                <h4 class="post_detail__title-title my-3 py-2">답변내용</h4>
                <div class="post_detail__body-title--button">
                    {% if request.user.is_superuser %}
                        <a href="{% url 'qna:answer_modify' answer.id  %}" class="btn btn-sm btn btn-warning">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-danger"
                            data-uri="{% url 'qna:answer_delete' answer.id  %}">삭제</a>
                    {% endif %}
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body">
                    <div class="post_detail__body-text card-text">
                        {{ answer.content|mark }}
                    </div>
                </div>
                <div class="d-flex justify-content-end" style="margin-bottom: 0.5rem;">
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        {% if answer.modify_date %}
                            {{ answer.modify_date_str }} (수정)
                        {% else %}
                            {{ answer.create_date_str }}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
</script>
{% endblock %}

templates/qna/question_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">질문 등록</span>
            <span class="navbar-img__text--subtitle">상명대학교 학우 여러분들의 의견에</span>
            <span class="navbar-img__text--subtitle">귀를 기울이는 학생회가 되겠습니다.</span>
        </div>
    </div>
    <div class="container" style="margin-top: 3rem;">
        <form method="post" class="post-form my-3">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3 row">
                <label for="subject" class="col-sm-1 col-form-label">제목</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control form-control-lg" name="subject" id="subject"
                           value="{{ form.subject.value|default_if_none:'' }}">
                            <!--입력 값이 없을 때 오류 발생을 표기-->
                </div>
                <div class="form-check col-auto mt-2" style="margin-left: 1rem;">
                    <input class="form-check-input" type="checkbox" name="anonymous" id="id_anonymous"
                    {% if form.anonymous.value %}
                        checked
                    {% endif %}>
                    <label class="form-check-label" for="id_anonymous">익명으로 작성하기</label>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="content" class="col-sm-1 col-form-label">내용</label>
                <div class="col-sm-10">
                    <textarea class="form-control form-control-lg" name="content"
                          id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
            </div>
            <div class="button">
                <button type="submit" class="btn btn-post_list btn-primary btn-lg rounded-pill" style="background-color: #273295;">작성 완료</button>
                <button class="btn btn-post_list btn-primary btn-lg rounded-pill" style="background-color: #343a40;" type="button" onclick="location.href='{% url 'qna:question_list' %}';">취소 하기</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/qna/question_list.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/boards.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" media="screen">
{% endblock %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">QnA 게시판</span>
            <span class="navbar-img__text--subtitle">상명대학교 제46대 총학생회 선[先]</span>
            <span class="navbar-img__text--subtitle">QnA 게시판입니다.</span>
        </div>
    </div>
    <section id="cont_view" class="cs_wrap">
        <div class="cs_tab">
            <div class="tab div3">
                <ul>
                    <li class="motion fadeInLeft visible" data-animation="fadeInLeft"><a href="{% url 'qna:terms' %}">이용약관</a></li>
                    <li class="motion fadeInLeft visible" data-animation="fadeInLeft"><a href="{% url 'qna:privacy' %}">개인정보처리방침</a></li>
                    <li class="motion fadeInLeft visible" data-animation="fadeInLeft"><a href="{% url 'qna:question_list' %}" class="on" title="현재">QnA 게시판</a></li>
                </ul>
            </div>
        </div>
		<div class="cs_area">
			<div class="cs_body ">
				<div class="wrap">
					<div class="ct_petitions">
						<div class="ct_petitions_area  ct_txt_left">
							<!-- 전체목록 -->
							<div class="ct_list1">
								<div class="board text">
{#									<div class="b_title">#}
{#                                        <a href="{% url 'qna:question_create' %}" class="btn btn-primary button-sm" style="float: right; margin-bottom: 5px;">질문 등록</a>#}
{#									</div>#}

									<div class="b_list category b_list2 board-text">
										<div class="bl_head cb" aria-hidden="true">
											<div class="bl_wrap">
												<div class="bl_category">상태</div>
												<div class="bl_subject">제목</div>
												<div class="bl_date">작성일</div>
												<div class="bl_agree">작성자</div>
											</div>
										</div>
										<div class="bl_body">
											<ul class="petition_list">
                                                {% if question_list %}
                                                    {% for question in question_list %}
                                                        <li style="padding:20px 0;">
                                                            <div class="bl_wrap">
                                                                <div class="bl_category ccategory cs wv_category">
                                                                    <span class="sound_only">상태 </span>
                                                                    {% if question.answer_set.count == 0 %}
                                                                        <p class="table-body__proceeding" style="margin: 0;">접수</p>
                                                                    {% else %}
                                                                        <p class="table-body__complete" style="margin: 0;">답변완료</p>
                                                                    {% endif %}
                                                                </div>
                                                                <div class="bl_subject">
                                                                    <a href="{% url 'qna:question_detail' question.pk %}" class="cb relpy_w">
                                                                        <span class="sound_only">제목 </span>{{ question.subject }}
                                                                    </a>
                                                                </div>
                                                                <div class="bl_date light">
                                                                    <span class="sound_only" >작성일 </span><span style="color: gray;">{{ question.date_str }}</span>
                                                                </div>
                                                                <div class="bl_agree cs">
                                                                    <span class="sound_only">작성자 </span>{{ question.author_name }}
                                                                </div>
                                                            </div>
                                                        </li>
                                                    {% endfor %}
                                                {% else %}
                                                    <li style="padding:20px 0;">
                                                        <div class="bl_wrap">
                                                            <div class="bl_category ccategory cs wv_category">
                                                                <span class="sound_only">상태 </span>
                                                            </div>
                                                            <div class="bl_subject">
                                                                <a href="#" class="cb relpy_w">
                                                                    <span class="sound_only">제목 </span>질문이 없습니다.
                                                                </a>
                                                            </div>
                                                            <div class="bl_date light">
                                                                <span class="sound_only">작성자 </span></div>
                                                            <div class="bl_agree cs">
                                                                <span class="sound_only">작성일 </span>
                                                            </div>
                                                        </div>
                                                    </li>
                                                {% endif %}
                                            </ul>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center" style="margin-bottom: 60px;">
                <!-- 이전페이지 -->
                {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="javascript:void(0);" onclick="changePage({{ question_list.previous_page_number }});">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in question_list.paginator.page_range %}
                    {% if page_number >= question_list.number|add:-3 and page_number <= question_list.number|add:3 %}
                        {% if page_number == question_list.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="javascript:void(0);" onclick="changePage({{ page_number }});">{{ page_number }}</a>
                        </li>
                        {% else %}
                        <li class="page-item">
                            <a class="page-link" href="javascript:void(0);" onclick="changePage({{ page_number }});">{{ page_number }}</a>
                        </li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="javascript:void(0);" onclick="changePage({{ question_list.next_page_number }});">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
		</div>
	</section>
{% endblock %}
{% block script %}
    <script>
        function changeValue() {
            var value = document.getElementById("categorys");
            let params = new URLSearchParams(location.search);
            params.set("category", value.options[value.selectedIndex].value);
            params.set("page", 1);
            window.open(location.pathname + '?' + params, '_self');
        }

        function changeSort() {
            var value = document.getElementById("sort");
            let params = new URLSearchParams(location.search);
            params.set("sort", value.options[value.selectedIndex].value);
            params.set("page", 1);
            window.open(location.pathname + '?' + params, '_self');
        }

        function changePage(page) {
            let params = new URLSearchParams(location.search);
            params.set("page", page);
            window.open(location.pathname + '?' + params, '_self');
        }

        function searchParam(key) {
          return new URLSearchParams(location.search).get(key);
        }

        const category = searchParam("category");
        const sort = searchParam("sort")
        if (category) {
            $('#categorys').val(category).prop("selected",true);
        }
        if (sort) {
            $('#sort').val(sort).prop("selected",true);
        }
    </script>
{% endblock %}

templates/qna/terms.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/terms.css' %}">
    <link rel="stylesheet" href="{% static 'css/boards.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" media="screen">
{% endblock %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}" />

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">이용약관</span>
            <span class="navbar-img__text--subtitle">상명대학교 청원 서비스 이용약관은</span>
            <span class="navbar-img__text--subtitle">다음과 같은 내용을 담고 있습니다.</span>
        </div>
    </div>
    <section id="cont_view" class="cs_wrap">
        <div class="cs_tab">
            <div class="tab div3">
                <ul>
                    <li class="motion fadeInLeft visible" data-animation="fadeInLeft"><a href="{% url 'qna:terms' %}" class="on" title="현재">이용약관</a></li>
                    <li class="motion fadeInLeft visible" data-animation="fadeInLeft"><a href="{% url 'qna:privacy' %}">개인정보처리방침</a></li>
                    <li class="motion fadeInLeft visible" data-animation="fadeInLeft"><a href="{% url 'qna:question_list' %}">QnA 게시판</a></li>
                </ul>
            </div>
        </div>
        <div class="login-container" style="display: block; padding:100px 0 40px 0;">
            <div class="white_sec">
                <div class="container">
                    <div class="info_box_wrapper">
                        {% include "accounts/info.html" %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}