accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('agree/', views.agree, name='agree'),
    path('change/', views.change_pw, name='change'),
    path('update/', views.update, name='update'),
    path('update/dept/<int:pk>/', views.change_dept, name='chage_dept'),
    path('find/', views.find_pw, name='find'),
    path('mypage/', views.mypage, name='mypage'),
    path('member_del/', views.member_del, name='member_del'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from petitions import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('petitions/', include('petitions.urls')),
    path('accounts/', include('accounts.urls')),
    path('qna/', include('qna.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

qna/urls.py
from django.urls import path

from qna import views

app_name = 'qna'

urlpatterns = [
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('questions/', views.question_list, name='question_list'),
    path('questions/<int:question_id>/', views.question_detail, name='question_detail'),
    # path('questions/create/', views.question_create, name='question_create'),
    path('questions/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('questions/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from config.settings import SUBTYPE_CHOICES_S, COLLEGE_CHOICES


class Year(models.Model):   # 학년도 테이블
    year = models.CharField(max_length=4)            # 학번
    major_i = models.IntegerField(default=0)         # 전심
    major_s = models.IntegerField(default=0)         # 전선
    culture = models.IntegerField(default=0)         # 교양 전체
    culture_cnt = models.IntegerField(default=0)     # 기초교양 개수
    all = models.IntegerField(default=0)             # 전체

    def __str__(self):
        return self.year


class Department(models.Model):     # 학과 테이블
    college = models.CharField(max_length=20, choices=COLLEGE_CHOICES)  # 소속 단과대
    name = models.CharField(max_length=20)  # 학과 이름
    type = models.CharField(max_length=2, choices=SUBTYPE_CHOICES_S)    # 균교 타입
    url = models.CharField(max_length=250, null=True, blank=True)       # 학과 교육과정 url
    def __str__(self):
        return f'[{self.college}] {self.name}'


class Profile(models.Model):    # 사용자 프로필
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)    # 장고 유저
    year = models.ForeignKey(Year, on_delete=models.CASCADE)                # 학번
    department = models.ForeignKey(Department, on_delete=models.CASCADE)    # 학과
    name = models.CharField(max_length=10)  # 본명

    def __str__(self):
        return f'[{self.year}] {self.user} {self.name} - {self.department}'

    def tostring(self):
        return f'{self.user.username} {self.name}'


class LoginHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # 장고 유저
    login_datetime = models.DateTimeField(auto_now_add=True)


class LoginHistory2(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)  # 장고 유저
    login_datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'LoginHistory'

    def __str__(self):
        return f'{self.user} - {self.login_datetime}'


class Statistics(models.Model):
    date = models.CharField(unique=True, max_length=10)
    visit_count = models.IntegerField(default=1)


class Statistics2(models.Model):
    date = models.CharField(unique=True, max_length=10)
    visit_count = models.IntegerField(default=1)

    class Meta:
        verbose_name = 'Statistics'

    def __str__(self):
        return f'{self.date} : {self.visit_count}'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

accounts/views.py
import datetime
from django.contrib import messages
from django.contrib.auth import login as auth_login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from sangmyung_univ_auth import auth

from accounts.ecampus import ecampus, information
from accounts.forms import UserForm
from accounts.models import Year, Department, Profile, LoginHistory2, Statistics2
from config.settings import DEPT_DIC
from petitions.models import Petition
import logging

logger = logging.getLogger('smu')


def agree(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username).exists():
            messages.error(request, '⚠️ 이미 가입된 학번입니다.')
            return redirect('accounts:agree')
        result = auth(username, password)
        if not result.is_auth:
            messages.error(request, '⚠️ 샘물 포털 ID/PW를 다시 확인하세요! (Caps Lock 확인)')
            return redirect('accounts:agree')
        context = result.body
        dept = context['department']
        if dept in DEPT_DIC.keys():
            dept = DEPT_DIC[dept]
        if not Department.objects.filter(name=dept):
            messages.error(request, '⚠️ 서비스에서 지원하지 않는 학과 입니다.')
            logger.error(f'서비스에서 지원하지 않는 학과와 학번\n학과: {dept}\n학번: {username[:4]}')
            return redirect('accounts:agree')
        context['id'], context['dept'] = username, dept
        request.session['context'] = context
        return redirect('accounts:register')

    departments = Department.objects.filter(url__isnull=False)
    dept_num = departments.count()
    response = render(request, 'accounts/agree.html', {'departments': departments, 'dept_num': dept_num})
    st, _ = Statistics2.objects.get_or_create(date=datetime.date.today())
    if request.COOKIES.get('is_visit') is None:
        response.set_cookie('is_visit', 'visited', 60*30)
        st.visit_count += 1
        st.save()
    return response


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            auth_login(request, user)
            LoginHistory2.objects.create(user=user)
            return redirect('petitions:petition_list', 'progress')
        if User.objects.filter(username=username):
            messages.error(request, '⚠️ 비밀번호를 확인하세요.')
        else:
            messages.error(request, '⚠️ 가입되지 않은 학번입니다.')
        return redirect('accounts:login')
    response = render(request, 'accounts/login.html')
    st, _ = Statistics2.objects.get_or_create(date=datetime.date.today())
    if request.COOKIES.get('is_visit') is None:
        response.set_cookie('is_visit', 'visited', 60 * 30)
        st.visit_count += 1
        st.save()
    return response


def register(request):
    context = request.session.get('context')

    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            year, _ = Year.objects.get_or_create(year=context['id'][:4])
            department = Department.objects.filter(name=context['dept']).first()
            if year and department:  # 지원하는 학과와 학번인지 확인
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                Profile.objects.create(user=user, year=year, department=department, name=context['name'])
                auth_login(request, user)  # 로그인
                LoginHistory2.objects.create(user=user)
                return redirect('petitions:petition_list', 'progress')
            messages.error(request, '⚠️ 서비스에서 지원하지 않는 학과 입니다.')
            return redirect('accounts:agree')
        messages.error(request, form.errors['password2'][0])
        return redirect('accounts:register')
    form = UserForm()
    context['form'] = form
    return render(request, 'accounts/register.html', context)


def change_pw(request):
    if request.method == "POST":
        user = request.user
        if not user.is_authenticated:
            user = get_object_or_404(User, username=request.POST["id"])
        if request.POST["password1"] == request.POST["password2"]:
            user.set_password(request.POST["password1"])
            user.save()
            messages.error(request, '비밀번호가 변경되었습니다.')
        else:
            messages.error("⚠️ 비밀번호가 일치하지 않습니다.")
    return redirect('home')


@login_required
def update(request):
    if request.method == "POST":
        password = request.POST["password"]
        result = auth(request.user.username, password)
        if result.is_auth:
            context = result.body
            dept = context['department']
            if dept in DEPT_DIC.keys():
                dept = DEPT_DIC[dept]
            department = Department.objects.filter(name=dept)
            if not department:
                messages.error(request, '⚠️ 서비스에서 지원하지 않는 학과 입니다.')
                return redirect('accounts:mypage')
            Profile.objects.filter(user=request.user).update(name=context['name'], department=department.first())
            messages.error(request, '회원 정보가 업데이트 되었습니다.')
            return redirect('accounts:mypage')
        messages.error(request, '⚠️ 샘물 포털 ID/PW를 다시 확인하세요! (Caps Lock 확인)')
    return redirect('accounts:mypage')


def find_pw(request):
    if request.method == "POST":
        username = request.POST["id"]
        password = request.POST["password1"]
        if not User.objects.filter(username=username):
            messages.error(request, '⚠️ 가입되지 않은 학번입니다.')
            return redirect('accounts:login')
        result = auth(username, password)
        if result.is_auth:
            return render(request, 'accounts/changePW.html', {'username': username})
    messages.error(request, '⚠️ 샘물 포털 ID/PW를 다시 확인하세요! (Caps Lock 확인)')
    return redirect('accounts:login')


@login_required
def change_dept(request, pk):
    profile = get_object_or_404(Profile, user=request.user)
    dept_dic = [7, 8, 9]
    if pk in dept_dic and profile.department.pk in dept_dic:
        department = get_object_or_404(Department, pk=pk)
        profile.department = department
        profile.save()
        messages.error(request, '전공이 변경되었습니다.')
        return redirect('petitions:petition_list', 'progress')
    messages.error(request, '⚠️ 변경 권한이 없습니다!')
    return redirect('home')


@login_required
def mypage(request):
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    page = request.GET.get('page', '1')
    petition_list = Petition.objects.filter(author=user).annotate(voter_count=Count('voter')).order_by('-create_date')
    paginator = Paginator(petition_list, 3)
    page_obj = paginator.get_page(page)
    return render(request, 'accounts/mypage.html', {'user': user, 'profile': profile, 'petition_list': page_obj})


@login_required
def member_del(request):
    if request.method == "POST":
        pw_del = request.POST["pw_del"]
        user = request.user
        if check_password(pw_del, user.password):
            user.delete()
            messages.error(request, '회원 탈퇴 되었습니다.')
            return redirect('home')
    messages.error(request, '⚠️ 비밀번호가 일치하지 않습니다.')
    return redirect('accounts:mypage')

templates/accounts/agree.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/terms.css' %}">
{% endblock %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}" />

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">이용약관 동의</span>
            <span class="navbar-img__text--subtitle">아래 사항을 모두 읽고 약관에 동의해주세요.</span>
        </div>
    </div>
    <div class="login-container" style="display: block;">
        <div class="white_sec">
            <div class="container">
                <!-- 검사 대상 박스 -->
                <div class="info_title"><b>이용약관</b></div>
                <div class="info_box_wrapper" style="margin-top: 1rem;">
                    {% include "accounts/info.html" %}
                    <!-- 동의 체크박스 -->
                    <div class="info_agree">
                        <label style='cursor: pointer;'>
                            <input type="checkbox" onclick="agree_func()" id="agree">
                            <label for='agree'></label>
                            &nbsp;다음 이용약관에 동의합니다.
                        </label>
                    </div>
                </div>
            </div>
        </div>

        <!-- 로그인 박스 -->
        <div class="info_title"><b>학생 인증</b></div>
        <div class="info_content" style="text-align: center; margin: 10px 0 0 0;">
            <p>
                샘물 통합로그인을 통해 재학생 인증을 진행합니다.<br>
                (<a href="https://portal.smu.ac.kr/" class="text-black footer_link" style="font-weight: bold;" target="_blank">상명대학교 샘물포털시스템</a> 학번/비밀번호)
            </p>
        </div>
        <div style="display: flex; justify-content: center;">
            <div class="login-form" style="margin-top: 10px; border:0.001px solid rgb(216, 216, 216); box-shadow: none;">
                <!-- 로그인 폼 -->
                <form onsubmit="return check_up();" method="post" >
                    {% csrf_token %}
                    <div class="agree">
                        <div class="input-group flex-nowrap">
                            <input type="text" class="form-control" name="username" id="id" placeholder="학번">
                        </div>
                        <div class="input-group flex-nowrap" style="margin-top: 1rem;">
                            <input type="password" class="form-control" name="password" id="pw" placeholder="샘물 비밀번호">
                        </div>
                        <div id="login_btn">
                            <div class='login_btn_default' style="color: rgb(1, 42, 127);">이용약관에 동의해주세요.</div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- 로딩 모달 창 -->
    <div id='m1' class="modal">
        <div class="load-modal-content">
            <div class="modal_loadcontainer">
                <div class="sk-chase">
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                </div>
                <div class="loading">
                    <span>인</span>
                    <span>증</span>
                    <span>정</span>
                    <span>보</span>
                    <span>확</span>
                    <span>인</span>
                    <span>중</span>
                    <span>.</span>
                    <span>.</span>
                    <span>.</span>
                </div>
                <div class="load_info">
                    창을 이동하지 마세요!
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
<script src="{% static 'js/modal.js' %}"></script>
<script>
    function agree_func() {
        var chk = document.getElementById('agree');
        // 체크시
        if (chk.checked) {
            var tag = "<input type='submit' class='btn btn-primary button-sm' value='인증하기' style='margin-top: 1rem;'>";
        }
        // 체크 풀시
        else {
            var tag = "<div class='login_btn_default'>이용약관에 동의해주세요.</div>";
        }
        document.getElementById("login_btn").innerHTML = tag;
    }

    // 인증하기 클릭시 modal 띄움
    function pop_modal() {
        document.getElementById('m1').style.display = "block";
    }

    // form 체크
    function check_up() {
        if (!document.getElementById('pw').value || !document.getElementById('id').value) {
            alert('⚠️ 학번과 샘물 비밀번호를 입력해주세요.');
            return false;
        }
        pop_modal();
        return true;
    }
</script>
{% endblock %}

templates/accounts/changePW.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}" />

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">비밀번호 변경</span>
            <span class="navbar-img__text--subtitle">비밀번호를 재설정해주세요.</span>
        </div>
    </div>
    <!-- 입력란 -->
    <div class="white_sec">
        <div class="container box_web" id="box_mobile">
            <form action="{% url 'accounts:change' %}" method="post" name='regi_form' onsubmit="return check_up()">
                {% csrf_token %}
                <label style="margin-top: 3rem;">ID</label>
                <input class="form-control" type="text" name="id" value="{{ username }}" style="background-color:rgb(248,249,250);" readonly>
                <label style="margin-top: 1rem;">비밀번호</label>
                <input class="form-control" id="pw1" type="password" name="password1" placeholder="비밀번호">
                <label style="margin-top: 1rem;">비밀번호 재확인</label>
                <input class="form-control" id="pw2" type="password" name="password2" placeholder="비밀번호 재확인">
                <div style="text-align: center; margin-top: 2rem; margin-bottom: 3rem;">
                    <input type='submit' class='btn btn-primary button-sm' value='변경하기'>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
<script>
    function check_up(){
        if(!document.getElementById('pw1').value){
            alert('😢 비밀번호를 입력해주세요.') ;
            regi_form.pw1.focus();
            return false;
        }
        if(document.getElementById('pw1').value !== document.getElementById('pw2').value){
            alert('😢 비밀번호가 일치하지 않습니다.') ;
            regi_form.pw1.focus();
            return false;
        }
        return true;
    }
</script>
{% endblock %}

templates/accounts/info.html
<div class="info_box">
    <div class="info_content">
        <p>
            1. 상명대학교 학생 청원은 소속원들이 학교 운영과 관련한 의견을 공유하고, 이에 대한 개선 요구를 총학생회를 통해 학교 측에 제시하여 직접 답변을 받을 수 있는 서비스입니다.
        </p>
        <p>2. <b>상명대학교 서울캠퍼스 구성원</b> 누구라도 청원 사이트 내 회원가입을 통해 만들어진 계정을 이용해 직접 청원 글을 작성하실 수 있습니다.</p>
        <p class="info_text">※ 상기 계정은 팀 <b>스뮤니티</b>가 운영하는 ‘<b>졸업 요건 검사 웹사이트</b>’에서 가입된 회원 정보와도 연동됩니다. 만약 위 페이지에서 개설한 계정이 있는 경우, 신규 회원가입이 따로 필요하지 않습니다.</p>
        <p>3. 승인된 청원은 학생 청원 페이지를 포함해 총학생회가 운영하는 소통창구를 통해 누구나 열람할 수 있으며, 모든 상명대학교 서울캠퍼스 구성원은 청원 동의에 참여할 수 있습니다. </p>
        <p>4. 한 번 청원 동의에 참여한다면, <b>동의에 대한 철회는 불가</b>하며, 하나의 청원 글에 대한 동의는 <b>1인 1동의를 원칙</b>으로 합니다.</p>
        <p>5. <b>100명 이상</b>의 청원 동의를 받은 청원은 본회 내 유관부서의 담당자 확인을 통해 특별한 사정이 없는 한 2주 이내 답변하여 청원 페이지에 게시됩니다.</p>
        <p>6. 중복, 비방, 욕설, 혐오 표현, 명예훼손 등 부적절한 청원 내용은 상명대학교 서울캠퍼스 총학생회와 스뮤니티가 운영하는 청원 운영 원칙에 따라 <b>숨김/삭제</b> 처리될 수 있습니다.</p>
        <p>7. 허위사실을 포함하거나, 타인을 악의적으로 비방 혹은 명예를 훼손하기 위한 목적으로 작성된 청원에는 답변이 어려울 수 있습니다.</p>
        <p>8. 유사한 성질이거나, 동일한 내용으로 청원이 중복 게시되어 있는 경우 가장 동의수가 많은 청원만 남기고 <b>반려</b>될 수 있습니다.</p>
    </div>
</div>

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>
        <div class="navbar-img__text">
            <span class="navbar-img__text--title">로그인</span>
            <span class="navbar-img__text--subtitle">학번과 스뮤니티 비밀번호를 입력해 주세요.</span>
        </div>
    </div>
   <!-- 로그인 박스 -->
    <div class="login-container">
        <div class="login-form">
            <div class="login_logo">
                <img id="login_logo" src="{% static 'img/logo2.png' %}" >
            </div>
            <form onsubmit="return check_up1();" method="post" action="{% url 'accounts:login' %}">
                {% csrf_token %}

                <div class="content">
                    <div class="input-group flex-nowrap">
                      <input type="text" class="form-control" name="username" id="id" placeholder="학번">
                    </div>
                    <div class="input-group flex-nowrap" style="margin-top: 1rem;">
                      <input type="password" class="form-control" name="password" id="pw" placeholder="비밀번호">
                    </div>
                    <a id="b2" class="link">비밀번호를 잊어버리셨나요?</a>
                </div>
                <div class="action">
                    <button id="login_button" type='submit'>로그인</button>
                    <button id="register_button" type="button" onclick="location.href='{% url 'accounts:agree' %}';">회원가입</button>
                </div>
            </form>
        </div>
    </div>

    <!-- 로그인시 로딩 모달 창 -->
    <div id='m1' class="modal">
        <div class="load-modal-content">
            <div class="modal_loadcontainer">
                <div class="sk-chase">
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                    <div class="sk-chase-dot"></div>
                </div>
                <div class="loading">
                    <span>인</span>
                    <span>증</span>
                    <span>정</span>
                    <span>보</span>
                    <span>확</span>
                    <span>인</span>
                    <span>중</span>
                    <span>.</span>
                    <span>.</span>
                    <span>.</span>
                </div>
                <div class="load_info">
                    창을 이동하지 마세요!
                </div>
            </div>
        </div>
    </div>

    <!-- 비밀번호 변경 -->
    <div id='m2' class="modal">
        <div class="update_modal_content">
            <div id='c2' class="close">&times;</div>
            <div class="modal-title">
                비밀번호 찾기
            </div>
            <div class="modal-expl" style="color: grey;">
                샘물 통합로그인을 통해 재학생 인증을 진행합니다.<br>
                (<a href="https://portal.smu.ac.kr/" style="font-weight: bold; color: grey; text-decoration: none;" target="_blank";>상명대학교 샘물포털시스템</a> 학번/비밀번호)
            </div>
            <hr style="width:100%; margin-top:1.3rem;">
            <!-- 폼 -->
            <form onsubmit="return check_up2();" method="post" action="{% url 'accounts:find' %}" name='form2'>
                {% csrf_token %}
                <div class="regi_box">
                    <input class="form-control" type="text" id="id2" name="id" placeholder='학번'>
                    <input class="form-control" type="password" id="pw2" name="password1" placeholder="샘물 비밀번호" style="margin-top: 1rem;">
                </div>
                <input type='submit' class='btn btn-primary button-sm' value='인증하기' style="margin:2.5rem 0 2rem 0;">
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
<script src="{% static 'js/modal.js' %}"></script>
<script>
    // 인증하기 클릭시 modal 띄움
    function pop_modal(){
        document.getElementById('m1').style.display = "block";
    }

    // ID/비번 안치면 빠꾸
    function check_up1() {
        if (!document.getElementById('pw').value || !document.getElementById('id').value) {
            alert('⚠️ 학번과 비밀번호를 입력해주세요.');
            return false;
        }
        pop_modal();
        return true;
    }
    function check_up2() {
        if (!document.getElementById('pw2').value || !document.getElementById('id2').value) {
            alert('⚠️ 학번과 샘물 비밀번호를 입력해주세요.');
            form2.pw2.focus();
            return false;
        }
        document.getElementById('m2').style.display = "none"
        pop_modal();
        return true;
    }

    var b2 = document.getElementById("b2");
    var m2 = document.getElementById('m2');
    var c2 = document.getElementById("c2");
    Btnclick(b2, m2);
    Spanclick(c2, m2);
    window.onclick = function (event) {
        if (event.target == m2) {
            m2.style.display = "none";
        }
    }
</script>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">회원가입</span>
            <span class="navbar-img__text--subtitle">스뮤니티 사이트의 고유 비밀번호를 설정해주세요.</span>
        </div>
    </div>
    <div class="white_sec">
        <div class="container box_web" id="box_mobile">
            <form method="post" name='regi_form' onsubmit="return check_up();">
                {% csrf_token %}
                    <label style="margin-top: 3rem;">이름</label>
                    <input class="form-control" type="text" name="name" value="{{ name }}" style="margin: auto; background-color:rgb(248,249,250);" readonly>

                    <label style="margin-top: 1rem;">학번</label>
                    <input class="form-control" type="text" name="username" value='{{ form.username.value|default_if_none:id }}' style="background-color:rgb(248,249,250);" readonly>

                    <label style="margin-top: 1rem;">학과</label>
                    <input class="form-control" type="text" name="department" value="{{ department }}" style="background-color:rgb(248,249,250);" readonly>

                    <label style="margin-top: 1rem;">이메일</label>
                    <input class="form-control" type="text" name="email" value='{{ form.email.value|default_if_none:email }}' style="background-color:rgb(248,249,250);" readonly>


                    <label style="margin-top: 1rem;">비밀번호</label>
                    <input class="form-control" id="pw1" type="password" name="password1" value="{{ form.password1.value|default_if_none:'' }}">
                    <div class='regi_guide' style="color: rgb(1, 42, 127);">
                        - 스뮤니티 사이트의 고유 비밀번호를 설정해주세요.
                    </div>
                    <label style="margin-top: 1rem;">비밀번호 재확인</label>
                    <input class="form-control" id="pw2" type="password" name="password2" value="{{ form.password2.value|default_if_none:'' }}">
                    <div style="text-align: center;">
                        <input type='submit' class='btn btn-primary button-sm' style="margin-top:2.5rem; margin-bottom: 3rem;" value='가입하기'>
                    </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function check_up(){
            if(!document.getElementById('pw1').value){
                alert('😢 비밀번호를 입력해주세요.') ;
                regi_form.pw1.focus();
                return false;
            }
            if(document.getElementById('pw1').value !== document.getElementById('pw2').value){
                alert('😢 비밀번호가 일치하지 않습니다.') ;
                regi_form.pw1.focus();
                return false;
            }
            return true;
        }
    </script>
{% endblock %}