accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('agree/', views.agree, name='agree'),
    path('change/', views.change_pw, name='change'),
    path('update/', views.update, name='update'),
    path('update/dept/<int:pk>/', views.change_dept, name='chage_dept'),
    path('find/', views.find_pw, name='find'),
    path('mypage/', views.mypage, name='mypage'),
    path('member_del/', views.member_del, name='member_del'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from petitions import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('petitions/', include('petitions.urls')),
    path('accounts/', include('accounts.urls')),
    path('qna/', include('qna.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

petitions/urls.py
from django.urls import path
from petitions import views

app_name = 'petitions'

urlpatterns = [
    path('<int:petition_id>/', views.petition_detail, name='petition_detail'),
    # path('create/', views.petition_create, name='petition_create'),   # 상명대학교 청원 운영 종료
    path('modify/<int:petition_id>/', views.petition_modify, name='petition_modify'),
    path('delete/<int:petition_id>/', views.petition_delete, name='petition_delete'),
    path('vote/<int:petition_id>/', views.petition_vote, name='petition_vote'),
    path('status/<str:status>/', views.petition_list, name='petition_list'),

    path('comment/create/<int:petition_id>/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    path('answer/create/<int:petition_id>/', views.answer_create, name='answer_create'),
    path('answer/create/<int:petition_id>/<str:type>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

qna/urls.py
from django.urls import path

from qna import views

app_name = 'qna'

urlpatterns = [
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('questions/', views.question_list, name='question_list'),
    path('questions/<int:question_id>/', views.question_detail, name='question_detail'),
    # path('questions/create/', views.question_create, name='question_create'),
    path('questions/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('questions/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="상명대학교 청원"/>
    <meta property="og:description" content="상명대학교 청원 사이트"/>
    <meta property="og:image" content="https://user-images.githubusercontent.com/63601183/261322036-fa4167e9-e45d-4fe4-b462-657ac3914065.png" />
    <meta property="og:url" content="https://smu-petition.com"/>
    <meta name="description" content="상명대학교 청원 사이트">
    <meta name="naver-site-verification" content="0532f1fcb411542727b7555821b0178df2547d21" />
    <meta name="google-site-verification" content="cUY8Gl2pP392gf90RN2h7ttSSmSyhK7wL-PQ0sn-WgA" />
    <title>상명대학교 청원</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen">
    <script src="https://kit.fontawesome.com/5b1d170f6d.js" crossorigin="anonymous"></script>
    {% block css %}
    {% endblock %}
</head>
<body>
    {% include "navbar.html" %}

    {% block content %}
    {% endblock %}

    {% include "footer.html" %}
    <!-- 예외처리 -->
    {% if messages %}
    {% for m in messages %}
    {% if m.tags == 'error' or m.tags == 'success' %}
    <script>
        alert('{{ m }}');
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
  <footer
          class="text-center text-lg-start text-white"
          style="background-color: #313131"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 display-none">
            <a href="https://www.student-smu.com" class="text-uppercase mb-4 font-weight-bold" target="_blank">
                <img src="{% static 'img/logo2.png' %}" width="2268" height="2268" style="width: 100px; height: 100px; background-color: #fff; border-radius: 50%;">
            </a>
          </div>
          <!-- Grid column -->


          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3 display-none">
            <h6 class="text-uppercase mb-4 font-weight-bold">
                Copyright
            </h6>
            <p>
              <a class="text-white footer_link" href="https://branched-verdict-a94.notion.site/Smunity-c4cf6107a91a49f8875c5c54373540d8?pvs=4" target="_blank">스뮤니티</a>
            </p>
            <p>
              <a class="text-white footer_link" href="https://www.student-smu.com" target="_blank">상명대학교 총학생회</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3 display-none">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Family Site
            </h6>
            <p>
              <a class="text-white footer_link" href="https://www.smu.ac.kr/ko/index.do" target="_blank">상명대학교</a>
            </p>
            <p>
              <a class="text-white footer_link" href="https://smunity.co.kr" target="_blank">상명대 졸업요건 검사</a>
            </p>
          </div>

          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3 display-none">
            <h6 class="text-uppercase mb-4 font-weight-bold">Privacy & Terms</h6>
              <p>
                  <a href="{% url 'qna:terms' %}" class="text-white footer_link">이용약관</a>
              </p>
              <p>
                  <a href="{% url 'qna:privacy' %}" class="text-white footer_link" target="_blank">개인정보처리방침</a>
              </p>
          </div>
          <!-- Grid column -->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3 display-none">

      <!-- Section: Copyright -->
      <section class="p-3 pt-0">
        <div class="row d-flex align-items-center">
          <!-- Grid column -->
          <div class="col-md-7 col-lg-8 text-center text-md-start">
            <!-- Copyright -->
            <div class="display">
                <a href="https://github.com/smu-nity/SMU-Petition" class="text-white footer_link" target="_blank">GitHub</a> | <a href="{% url 'qna:privacy' %}" class="text-white footer_link" target="_blank">개인정보처리방침</a> | <a href="{% url 'qna:terms' %}" class="text-white footer_link">이용약관</a>
            </div>
            <div class="p-3">
                <a class="text-white footer_link" href="https://branched-verdict-a94.notion.site/Smunity-c4cf6107a91a49f8875c5c54373540d8?pvs=4" target="_blank">
                    Copyright ⓒ Smunity
                </a>
            </div>
            <!-- Copyright -->
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
            <!-- Instagram -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               href="https://www.instagram.com/smu_1st/"
               target="_blank"
               ><i class="fab fa-instagram"></i
              ></a>

            <!-- Youtube -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               href="https://www.youtube.com/channel/UCKfo9NabKyviW5jDi3xBngg"
               target="_blank"
               ><i class="fab fa-youtube"></i
              ></a>

            <!-- Mail -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               href="mailto:smu.first2023@gmail.com"
               ><i class="fas fa-envelope"></i
              ></a>

            <!-- Kakao -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               href="https://open.kakao.com/o/sXKtjVbf"
               target="_blank"
               >
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 256 256">
                    <path fill="#ffffff" d="M128 36C70.562 36 24 72.713 24 118c0 29.279 19.466 54.97 48.748 69.477-1.593 5.494-10.237 35.344-10.581 37.689 0 0-.207 1.762.934 2.434s2.483.15 2.483.15c3.272-.457 37.943-24.811 43.944-29.04 5.995.849 12.168 1.29 18.472 1.29 57.438 0 104-36.712 104-82 0-45.287-46.562-82-104-82z"/>
                    <path fill="#494949" d="M70.5 146.625c-3.309 0-6-2.57-6-5.73V105.25h-9.362c-3.247 0-5.888-2.636-5.888-5.875s2.642-5.875 5.888-5.875h30.724c3.247 0 5.888 2.636 5.888 5.875s-2.642 5.875-5.888 5.875H76.5v35.645c0 3.16-2.691 5.73-6 5.73zM123.112 146.547c-2.502 0-4.416-1.016-4.993-2.65l-2.971-7.778-18.296-.001-2.973 7.783c-.575 1.631-2.488 2.646-4.99 2.646a9.155 9.155 0 0 1-3.814-.828c-1.654-.763-3.244-2.861-1.422-8.52l14.352-37.776c1.011-2.873 4.082-5.833 7.99-5.922 3.919.088 6.99 3.049 8.003 5.928l14.346 37.759c1.826 5.672.236 7.771-1.418 8.532a9.176 9.176 0 0 1-3.814.827c-.001 0 0 0 0 0zm-11.119-21.056L106 108.466l-5.993 17.025h11.986zM138 145.75c-3.171 0-5.75-2.468-5.75-5.5V99.5c0-3.309 2.748-6 6.125-6s6.125 2.691 6.125 6v35.25h12.75c3.171 0 5.75 2.468 5.75 5.5s-2.579 5.5-5.75 5.5H138zM171.334 146.547c-3.309 0-6-2.691-6-6V99.5c0-3.309 2.691-6 6-6s6 2.691 6 6v12.896l16.74-16.74c.861-.861 2.044-1.335 3.328-1.335 1.498 0 3.002.646 4.129 1.772 1.051 1.05 1.678 2.401 1.764 3.804.087 1.415-.384 2.712-1.324 3.653l-13.673 13.671 14.769 19.566a5.951 5.951 0 0 1 1.152 4.445 5.956 5.956 0 0 1-2.328 3.957 5.94 5.94 0 0 1-3.609 1.211 5.953 5.953 0 0 1-4.793-2.385l-14.071-18.644-2.082 2.082v13.091a6.01 6.01 0 0 1-6.002 6.003z"/>
                </svg>
            </a>
          </div>
          <!-- Grid column -->
        </div>
      </section>
      <!-- Section: Copyright -->
    </div>
    <!-- Grid container -->
  </footer>
  <!-- Footer -->

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/home.html
<!doctype html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" media="screen">
</head>
<body>
    {% include "navbar.html" %}

    <section>
        <div class="container main_bg">
            <div class="row justify-content-between">
                <div class="col-lg-6 text-light"></div>
                <div class="col-lg-5 mt-5">
                    <br><br><br><br><br><br>
                    <h1 class="display-1 fw-bold lh-1 mb-5 text-light">Smunity</h1>
                    <p class="col-lg-10 fs-1 text-light">상명대학교<br>청원 사이트</p>
                </div>
            </div>
        </div>
    </section>

    {% include "footer.html" %}
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</html>

templates/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-nav px-1 py-1">
        <a href="{% url 'home' %}" class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none">
            <img src="{% static 'img/logo.png' %}" class="logo_img">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link fs-5 a_tag" href="{% url 'qna:question_list' %}">QnA</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link fs-5 a_tag" href="{% url 'qna:terms' %}">이용안내</a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link fs-5 a_tag" href="{% url 'petitions:petition_create' %}">청원하기</a>#}
{#                </li>#}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link fs-5 a_tag" href="{% url 'petitions:petition_list' 'progress'%}">모든 청원</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link fs-5 a_tag" href="/admin/">관리자 페이지</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link fs-5 a_tag" href="{% url 'accounts:mypage' %}">마이페이지</a>
                        </li>
                    {% endif %}
                <li class="nav-item">
                    <a class="nav-link fs-5 a_tag" href="{% url 'accounts:logout' %}">로그아웃</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link fs-5 a_tag" href="{% url 'accounts:login' %}">로그인</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>