config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from petitions import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('petitions/', include('petitions.urls')),
    path('accounts/', include('accounts.urls')),
    path('qna/', include('qna.urls')),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain')),
]

petitions/urls.py
from django.urls import path
from petitions import views

app_name = 'petitions'

urlpatterns = [
    path('<int:petition_id>/', views.petition_detail, name='petition_detail'),
    # path('create/', views.petition_create, name='petition_create'),   # 상명대학교 청원 운영 종료
    path('modify/<int:petition_id>/', views.petition_modify, name='petition_modify'),
    path('delete/<int:petition_id>/', views.petition_delete, name='petition_delete'),
    path('vote/<int:petition_id>/', views.petition_vote, name='petition_vote'),
    path('status/<str:status>/', views.petition_list, name='petition_list'),

    path('comment/create/<int:petition_id>/', views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),

    path('answer/create/<int:petition_id>/', views.answer_create, name='answer_create'),
    path('answer/create/<int:petition_id>/<str:type>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

qna/urls.py
from django.urls import path

from qna import views

app_name = 'qna'

urlpatterns = [
    path('terms/', views.terms, name='terms'),
    path('privacy/', views.privacy, name='privacy'),
    path('questions/', views.question_list, name='question_list'),
    path('questions/<int:question_id>/', views.question_detail, name='question_detail'),
    # path('questions/create/', views.question_create, name='question_create'),
    path('questions/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('questions/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
]

petitions/models.py
from datetime import datetime

import pytz
from django.db import models
from django.contrib.auth.models import User

from accounts.models import Profile
from config.settings import CATEGORY_CHOICES, STATUS_CHOICES, TIME_ZONE, SUCCESS_VALUE


class Petition(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_petition')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)
    anonymous = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)

    def __str__(self):
        return f'[{self.author}] {self.subject} ({self.create_date})'

    def author_name(self):
        if self.anonymous:
            return '익명'
        profile = Profile.objects.filter(user=self.author)
        if profile:
            return profile.first().name
        return self.author.username

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)

    def end_date_str(self):
        return date_format(self.end_date)

    def period_str(self):
        return f'{date_format(self.create_date)} ~ {date_format(self.end_date)}'

    def d_day(self):
        if self.status == 1:
            day = (self.end_date.date() - datetime.now().date()).days
            day = day if day != 0 else 'Day'
            return f'| D-{day}'
        return ''

    def get_percentage(self):
        return 100 if self.voter.count() >= int(SUCCESS_VALUE) else (self.voter.count() * 100) // int(SUCCESS_VALUE)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    petition = models.ForeignKey(Petition, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'[{self.petition.subject}] {self.content} ({self.create_date})'

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='petition_answer')
    petition = models.ForeignKey(Petition, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'[{self.author}] {self.petition.subject} ({self.create_date})'

    def create_date_str(self):
        return time_format(self.create_date)

    def modify_date_str(self):
        return time_format(self.modify_date)


def time_format(time):
    return time.astimezone(pytz.timezone(TIME_ZONE)).strftime("%m/%d %H:%M")


def date_format(time):
    return time.astimezone(pytz.timezone(TIME_ZONE)).strftime("%y.%m.%d")

petitions/forms.py
from django import forms
from petitions.models import Petition, Comment, Answer


class PetitionForm(forms.ModelForm):
    class Meta:
        model = Petition
        fields = ['subject', 'content', 'category', 'anonymous']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

petitions/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from accounts.models import Statistics2
from config.settings import SUCCESS_VALUE, DEADLINE_VALUE, CSRF_TRUSTED_ORIGINS
from petitions.models import Petition, Comment, Answer
from django.http import HttpResponseNotAllowed

from .decorators import superuser_required
from .forms import PetitionForm, CommentForm, AnswerForm
from django.contrib import messages


def preprocess(queryset):
    q_list = list(queryset)
    for _ in range(2-len(q_list)):
        q_list.append(None)
    return q_list


def home(request):
    plist, context = Petition.objects.filter(status__in=[1, 2]).order_by('-create_date'), {}
    if plist:
        plist_v = plist.annotate(voter_count=Count('voter')).order_by('-voter_count', '-create_date')
        plist_d = plist.order_by('end_date')
        petition_list  = [{'top1': plist_v[0], 'top2_3': preprocess(plist_v[1:3])}, {'top1': plist_d[0], 'top2_3': preprocess(plist_d[1:3])}, {'top1': plist[0], 'top2_3': preprocess(plist[1:3])}]
        context = {'petition_list': petition_list, 'top2_3': plist_v[1:3]}
    response = render(request, 'petitions/home.html', context)
    if request.COOKIES.get('is_visit') is None:
        response.set_cookie('is_visit', 'visited', 60*30)
        st, _ = Statistics2.objects.get_or_create(date=datetime.date.today())
        st.visit_count += 1
        st.save()
    return response


def petition_list(request, status):
    status_dic = {'progress': [1], 'established': [2, 3], 'unestablished': [4, 5]}
    sort_dic = {'0': '-create_date', '1': '-voter_count', '2': 'create_date'}
    pl = Petition.objects.filter(status__in=status_dic[status]).annotate(voter_count=Count('voter'))
    category = request.GET.get('category', '0')
    stats = request.GET.get('status', '0')
    sort = request.GET.get('sort', '0')
    page = request.GET.get('page', '1')
    if category != '0':
        pl = pl.filter(category=int(category))
    if stats != '0':
        pl = pl.filter(status=int(stats))
    pl = pl.order_by(sort_dic[sort])
    paginator = Paginator(pl, 5)
    page_obj = paginator.get_page(page)
    response = render(request, 'petitions/petition_list.html', {'petition_list': page_obj, 'page': '모든 청원', 'status': status})
    if request.COOKIES.get('is_visit') is None:
        response.set_cookie('is_visit', 'visited', 60 * 30)
        st, _ = Statistics2.objects.get_or_create(date=datetime.date.today())
        st.visit_count += 1
        st.save()
    return response


def petition_detail(request, petition_id):
    petition = get_object_or_404(Petition, pk=petition_id)
    comment_list = Comment.objects.filter(petition=petition).order_by('-create_date')
    page = request.GET.get('page', '1')
    paginator = Paginator(comment_list, 5)
    page_obj = paginator.get_page(page)
    url = f'{CSRF_TRUSTED_ORIGINS[0]}/petitions/{petition.pk}/'
    context = {'petition': petition, 'comment_list': page_obj, 'url': url}
    answers = Answer.objects.filter(petition=petition)
    if answers:
        context['answer'] = answers.first()
    response = render(request, 'petitions/petition_detail.html', context)
    if request.COOKIES.get('is_visit') is None:
        response.set_cookie('is_visit', 'visited', 60 * 30)
        st, _ = Statistics2.objects.get_or_create(date=datetime.date.today())
        st.visit_count += 1
        st.save()
    return response


@login_required
def petition_create(request):
    if request.method == 'POST':
        form = PetitionForm(request.POST)
        if form.is_valid():
            petition = form.save(commit=False)
            petition.author = request.user
            petition.end_date = datetime.datetime.now() + datetime.timedelta(days=int(DEADLINE_VALUE))
            petition.save()
            return redirect('petitions:petition_list', 'progress')
    else:
        form = PetitionForm()
    context = {'form': form}
    return render(request, 'petitions/petition_form.html', context)


@login_required
def petition_modify(request, petition_id):
    petition = get_object_or_404(Petition, pk=petition_id)
    if request.user != petition.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('petitions:petition_detail', petition_id=petition.id)
    if request.method == "POST":
        form = PetitionForm(request.POST, instance=petition)
        if form.is_valid():
            petition = form.save(commit=False)
            petition.modify_date = timezone.now()  # 수정일시 저장
            petition.save()
            return redirect('petitions:petition_detail', petition_id=petition.id)
    else:
        form = PetitionForm(instance=petition)
    context = {'form': form}
    return render(request, 'petitions/petition_form.html', context)


@login_required
def petition_delete(request, petition_id):
    petition = get_object_or_404(Petition, pk=petition_id)
    if request.user != petition.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('petitions:petition_detail', petition_id=petition.id)
    petition.delete()
    return redirect('petitions:petition_list', 'progress')


@login_required
def petition_vote(request, petition_id):
    petition = get_object_or_404(Petition, pk=petition_id)
    if petition.status == 3:
        messages.error(request, '답변완료된 청원입니다.')
    elif petition.status == 4:
        messages.error(request, '만료된 청원입니다.')
    elif petition.status == 5:
        messages.error(request, '반려된 청원입니다.')
    elif request.user == petition.author:
        messages.error(request, '본인이 작성한 청원에 동의할 수 없습니다.')
    elif request.user in petition.voter.all():
        messages.error(request, '이미 동의한 청원입니다.')
    else:
        petition.voter.add(request.user)
        if petition.voter.count() >= int(SUCCESS_VALUE):
            petition.status = 2
            petition.save()
            messages.success(request, '해당 청원에 대한 동의 처리가 완료되었습니다.')
    return redirect('petitions:petition_detail', petition_id=petition.id)


@login_required
def comment_create(request, petition_id):
    petition = get_object_or_404(Petition, pk=petition_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.petition = petition
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('petitions:petition_detail', petition_id=petition.id), comment.id))
        else:
            messages.error(request, '댓글을 입력해주세요.')
            return redirect('petitions:petition_detail', petition_id=petition.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    return render(request, 'petitions/petition_detail.html', {'petition': petition, 'form': form})


@login_required
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('petitions:petition_detail', petition_id=comment.petition.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('petitions:petition_detail', petition_id=comment.petition.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    return render(request, 'petitions/answer_form.html', {'form': form, 'content': '댓글 수정', 'petition_id': comment.petition.id})


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('petitions:petition_detail', petition_id=comment.petition.id)


@superuser_required
def answer_create(request, petition_id, type=None):
    petition = get_object_or_404(Petition, pk=petition_id)
    if Answer.objects.filter(petition=petition):
        messages.error(request, '이미 답변한 청원입니다.')
        return redirect('petitions:petition_detail', petition_id=petition.id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.petition = petition
            answer.save()
            petition.status = 3
            if type == 'reject':
                petition.status = 5
            petition.end_date = datetime.datetime.now()
            petition.save()
            return redirect('petitions:petition_detail', petition_id=petition.id)
    else:
        form = AnswerForm()
    content = '답변 등록'
    if type == 'reject':
        content = '반려 이유'
    return render(request, 'petitions/answer_form.html', {'form': form, 'content': content, 'petition': petition})


@superuser_required
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('petitions:petition_detail', petition_id=answer.petition.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, 'petitions/answer_form.html', {'form': form, 'content': '답변 등록', 'petition': answer.petition})


@superuser_required
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

templates/petitions/answer_form.html
{% extends 'base.html' %}
{% load static %}
{% load petitions_filter %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">{{ content }}</span>
            <span class="navbar-img__text--subtitle">상명대학교 학우 여러분들의 의견에</span>
            <span class="navbar-img__text--subtitle">귀를 기울이는 학생회가 되겠습니다.</span>
        </div>
    </div>
    <div class="post_detail__body_container container my-3" style="margin-bottom: 3rem !important;">
        <div class="post_detail__body-title border-bottom">
            <h4 class="post_detail__title-title my-3 py-2">청원내용</h4>
        </div>
        <div class="card my-3">
            <div class="card-body">
                <div class="post_detail__body-text card-text">
                    {{ petition.content|mark }}
                </div>
            </div>
            <div class="d-flex justify-content-end" style="margin-bottom: 0.5rem;">
                <div class="badge bg-light text-dark p-2 text-start">
                    {{ petition.author_name }}
                </div>
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    {% if petition.modify_date %}
                        {{ petition.modify_date_str }} (수정)
                    {% else %}
                        {{ petition.create_date_str }}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="post_detail__body-title border-bottom">
            <h4 class="post_detail__title-title my-3 py-2">답변내용</h4>
        </div>
        <form method="post" class="my-3">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <textarea class="form-control" name="content" id="content"
                          rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <div class="button">
                <button type="submit" class="btn btn-post_list btn-primary btn-lg rounded-pill" style="background-color: #273295;">작성 완료</button>
                <button class="btn btn-post_list btn-primary btn-lg rounded-pill" style="background-color: #343a40;" type="button" onclick="location.href='{% url 'petitions:petition_detail' petition.id %}';">취소 하기</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/petitions/petition_detail.html
{% extends 'base.html' %}
{% load static %}
{% load petitions_filter %}
{% block content %}
    <div class="navbar-img">
        <img class="navbar-img-image" src="{% static 'img/main.jpg' %}"/>

        <div class="navbar-img__text">
            <span class="navbar-img__text--title">청원 게시판</span>
            <span class="navbar-img__text--subtitle">상명대학교 학우 여러분들의 의견에</span>
            <span class="navbar-img__text--subtitle">귀를 기울이는 학생회가 되겠습니다.</span>
        </div>
    </div>
    <div>
        <div class="post_detail__title_container container my-3">
            <!-- message 표시 -->
            {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                <div class="alert alert-danger my-3" role="alert">
                    <strong>{{ message.tags }}</strong>
                    <ul><li>{{ message.message }}</li></ul>
                </div>
                {% endif %}
            {% endfor %}
            {% endif %}
            <!-- 청원 -->
            <div class="post_detail__title">
                {% if petition.status == 3 %}
                    <h4 class="py-2 post_detail__title-status table-body__complete" style="margin-bottom: 0;">[{{ petition.get_status_display }}]</h4>
                {% else %}
                    <h4 class="py-2 post_detail__title-status table-body__proceeding" style="margin-bottom: 0;">[{{ petition.get_status_display }}]</h4>
                {% endif %}
                <h5 class="py-2 post_detail__title-status">({{ petition.period_str }})</h5>
                <h3 class="py-2 post_detail__title-title" style="text-align: center; margin-top: 16px; margin-bottom: 0;">{{ petition.subject }}</h3>
                <h4 class="py-2 post_detail__title-agree">총 <b style="color: rgb(1, 42, 127); margin-bottom: 0;">{{petition.voter.count}}</b> 명이 동의했습니다.</h4>
            </div>
        </div>

    <div class="post_detail__body_container container my-3" style="margin-bottom: 3rem !important;">
        <div class="post_detail__body-title border-bottom">
            <h4 class="post_detail__title-title my-3 py-2">청원내용</h4>
            <div class="post_detail__body-title--button">
                {% if request.user.is_superuser and not answer %}
                    {% if petition.status == 2 %}
                        <a href="{% url 'petitions:answer_create' petition.id %}" class="btn btn-sm btn-primary">답변 등록</a>
                    {% endif %}
                    <a href="{% url 'petitions:answer_create' petition.id 'reject' %}" class="btn btn-sm btn-primary">청원 반려</a>
                {% endif %}
                {% if request.user == petition.author %}
                    <a href="{% url 'petitions:petition_modify' petition.id  %}" class="btn btn-sm btn btn-warning">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-danger"
                        data-uri="{% url 'petitions:petition_delete' petition.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
        <div class="card my-3">
            <div class="card-body">
                <div class="post_detail__body-text card-text">
                    {{ petition.content|mark }}
                </div>
            </div>
            <div class="d-flex justify-content-end" style="margin-bottom: 0.5rem;">
                <div class="badge bg-light text-dark p-2 text-start">
                    {{ petition.author_name }}
                </div>
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    {% if petition.modify_date %}
                        {{ petition.modify_date_str }} (수정)
                    {% else %}
                        {{ petition.create_date_str }}
                    {% endif %}
                </div>
            </div>
        </div>

        {% if answer %}
            <div class="post_detail__body-title border-bottom">
                <h4 class="post_detail__title-title my-3 py-2">답변내용</h4>
                <div class="post_detail__body-title--button">
                    {% if request.user.is_superuser %}
                        <a href="{% url 'petitions:answer_modify' answer.id  %}" class="btn btn-sm btn btn-warning">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-danger"
                            data-uri="{% url 'petitions:answer_delete' answer.id  %}">삭제</a>
                    {% endif %}
                </div>
            </div>
            <div class="card my-3">
                <div class="card-body">
                    <div class="post_detail__body-text card-text">
                        {{ answer.content|mark }}
                    </div>
                </div>
                <div class="d-flex justify-content-end" style="margin-bottom: 0.5rem;">
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        {% if answer.modify_date %}
                            {{ answer.modify_date_str }} (수정)
                        {% else %}
                            {{ answer.create_date_str }}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="post_detail__body-button my-3">
            {% if petition.status == 1 or petition.status == 2 %}
                <a href="javascript:void(0)" data-uri="{% url 'petitions:petition_vote' petition.id  %}"
                    class="btn btn-primary navbarMain-button recommend">
                        <i class="fas fa-thumbs-up enroll-btn__icon"></i>
                        <span>동의하기</span>
                        <span class="badge rounded-pill bg-success" style="margin-left: 10px; background-color: #fff !important; color: rgb(1, 42, 127);">{{petition.voter.count}}</span>
                </a>
            {% else %}
                <a class="btn btn-primary navbarMain-button">
                    <i class="fas fa-thumbs-up enroll-btn__icon"></i>
                    <span>참여인원</span>
                    <span class="badge rounded-pill bg-success" style="margin-left: 10px; background-color: #fff !important; color: rgb(1, 42, 127);">{{petition.voter.count}}</span>
                </a>
            {% endif %}
        <h5 class="post_detail__body-share--title" style="margin-top: 2rem;">공유하기</h5>
            <div class="container post_detail__body-share--url">
                <div class="row">
                    <div class="col-sm-2 post_detail__body-share--button post_detail__body-share--button--url">URL
                    </div>
                    <div id="url" class="col-sm-8 post_detail__body-share--button"></div>
                    <button class="col-sm-2 post_detail__body-share--button post_detail__body-share--button--copy" onclick="clip();">
                        복사
                    </button>
                </div>
            </div>
        </div>

        <form action="{% url 'petitions:comment_create' petition.id %}" method="post" class="my-3">
            {% csrf_token %}
            <div class="mb-3">
                <div class="post_detail__body-title border-bottom">
                    <h4 class="post_detail__title-title my-3 py-2">댓글달기</h4>
                    <div class="post_detail__body-title--button">
                        <input type="submit" value="댓글등록" class="btn btn-primary button-sm">
                    </div>
                </div>
                <textarea name="content" id="content" class="form-control" rows="2"></textarea>
            </div>
        </form>

        <!-- 답변 -->
        <h5 class="border-bottom my-3 py-2">{{petition.comment_set.count}}개의 댓글이 있습니다.</h5>
        <ul class="comment_data-container list-group list-group-flush">
            {% for comment in comment_list %}
            <li class="list-group-item border-bottom comment_data-list">
                <a id="comment_{{ comment.id }}"></a>
                <div class="comment_data-content">
                    <div class="commnet_data-left">
                        <div class="comment_data-order">
                            <div>#{{ comment_list.paginator.count|sub:comment_list.start_index|sub:forloop.counter0|add:1 }}</div>
                        </div>
                        <div class="comment_data-agree">
                            <div>{{ comment.content|mark }}</div>
                        </div>
                    </div>
                    <div class="comment_data-right">
                        <div class="comment_data-date">
                            <div class="comment_data-time">
                                {% if comment.modify_date %}
                                    {{ comment.modify_date_str }} (수정)
                                {% else %}
                                    {{ comment.create_date_str }}
                                {% endif %}
                            </div>
                            <div class="my-3 comment_data-button">
                            {% if request.user == comment.author %}
                                <a href="{% url 'petitions:comment_modify' comment.id  %}" class="btn btn-sm btn btn-warning">수정</a>
                                <a href="javascript:void(0)" class="delete btn btn-sm btn-danger" data-uri="{% url 'petitions:comment_delete' comment.id  %}">삭제</a>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center comment_data-pagination">
            <!-- 이전페이지 -->
            {% if comment_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="javascript:void(0);" onclick="changePage({{ comment_list.previous_page_number }});">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in comment_list.paginator.page_range %}
                {% if page_number >= comment_list.number|add:-3 and page_number <= comment_list.number|add:3 %}
                    {% if page_number == comment_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="javascript:void(0);" onclick="changePage({{ page_number }});">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0);" onclick="changePage({{ page_number }});">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if comment_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="javascript:void(0);" onclick="changePage({{ comment_list.next_page_number }});">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    var url = "{{ url }}";
    document.getElementById("url").innerHTML = url;

    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("해당 청원에 동의하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    function changePage(page) {
        let params = new URLSearchParams(location.search);
        params.set("page", page);
        window.open(location.pathname + '?' + params, '_self');
    }

    function clip(){
        var url = '';
        var textarea = document.createElement("textarea");
        document.body.appendChild(textarea);
        url = "{{ url }}";
        textarea.value = url;
        textarea.select();
        document.execCommand("copy");
        document.body.removeChild(textarea);
        alert("URL이 복사되었습니다.")
    }
</script>
{% endblock %}